// Personality profile generated by the LLM
export interface ClarityProfile {
  threeWords: [string, string, string]; // 3 words summarizing personality
  strengths: string[]; // 2–3 strengths
  challenges: string[]; // 2–3 challenges
  preferredTone: string; // e.g., "Warm but direct"
  adviceStyle: string; // e.g., "One small step at a time"
  summary: string; // 2–3 sentence human-readable summary
}

// Chat message
export interface ChatMessage {
  sender: "user" | "ai";
  message: string;
  timestamp: number;
}

// Onboarding answer
export interface Answer {
  questionId: number;
  value: string; // Option ID for MC ("a","b","c") or free text for OE
}

// API request/response types
export interface OnboardingRequest {
  answers: Answer[];
}

export interface OnboardingResponse {
  clarityProfile: ClarityProfile;
}

export interface ChatRequest {
  clarityProfile: ClarityProfile;
  sessionMessages: ChatMessage[];
}

export interface ChatResponse {
  aiMessage: string;
}
